[package]
name = "exif-rename"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.30"
clap = { version = "4.4.2", features = ["derive"] }
regex = "1.9.5"
strfmt = "0.2.4"

[dev-dependencies]
assert_cmd = "2.0.12"
